version: '2'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "./.data/db:/var/lib/mysql"
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    links:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      # WORDPRESS_DB_USER: root
      # WORDPRESS_DB_NAME: dvd
      # WORDPRESS_TABLE_PREFIX: wr